Attica-org/athens-backend

src/main/resources/application.yml

active pord 추가

---

src/main/java/com/attica/athens/domain/agora/api/AgoraController.java
src/main/java/com/attica/athens/global/config/SecurityConfig.java
src/main/resources/application-prod.yml

- 배포 서버에서 기대했던 응답 스펙과 다른 부분을 변경 했습니다.
<br>
---

Agora 응답 수정

---

src/main/java/com/attica/athens/domain/agoraUser/application/AgoraUserService.java

- 메타 정보 조회 엔드포인트(uri)를 수정했습니다.
<br>
---

refactor: 메타 정보 조회 엔드포인트 수정

---

src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
src/main/java/com/attica/athens/domain/agoraUser/dao/AgoraUserRepository.java

- 관찰자는 종료 투표 못하도록 수정한다.
<br>
---

fix: 관찰자는 종료 투표 못하도록 수정

---

src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java

- session을 가진 아고라 참여자를 조회하도록 수정
<br>
---

sessionId로 참여자 조회

---

src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java

Dev-> Main

---

src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java

resolved: #123 
- 조회 쿼리 수정
<br>
---

참여자 조회 타입 쿼리 수정

---

src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepository.java
src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
src/main/resources/application-prod.yml

- 키워드 기반 아고라 리스트 조회 수정
- 카테고리 기반 아고라 리스트 조회 방식과 같음
<br>
---

fix : 키워드 기반 아고라 리스트 조회 수정

---

build.gradle
docker-compose.yml
src/main/resources/application-prod.yml
src/main/resources/logback-prod.xml

- prod 환경에서 로그를 파일로 저장한다.
<br>
---

logback.xml 추가

---

build.gradle
src/main/java/com/attica/athens/domain/common/aspect/RequestLogAspect.java
src/main/resources/logback-prod.xml

- 요청 로깅 Aspect를 추가했습니다.
<br>
---

요청 로깅 AOP 추가

---

src/main/java/com/attica/athens/domain/common/advice/ErrorResponse.java
src/main/java/com/attica/athens/domain/common/advice/GlobalExceptionHandler.java
src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
src/test/java/com/attica/athens/domain/agora/AgoraOpenApiIntegrationTest.java

- [#146] 
- 특정 예외에 대한 response meessage 형식을 변경했습니다. (string -> json)
- 형식 변경에 의한 테스트 코드 수정
<br>
---

응답 형식 변경 및 테스트 코드 수정

---

.github/workflows/backend-cd.yaml
.github/workflows/backend-ci.yaml
Dockerfile
Jenkinsfile
deploy-prod.sh
docker-compose.blue.yml
docker-compose.green.yml
src/main/java/com/attica/athens/domain/sample/HealthCheckController.java

- jenkins 배포 자동화
- 무중단 배포 설정
<br>
---

애플리케이션 무중단 배포 스크립트 추가

---

src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java
src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
src/main/java/com/attica/athens/domain/chat/dao/ReactionRepository.java
src/main/java/com/attica/athens/domain/chat/domain/ChatType.java
src/main/java/com/attica/athens/domain/chat/domain/Reaction.java
src/main/java/com/attica/athens/domain/chat/domain/ReactionType.java
src/main/java/com/attica/athens/domain/chat/dto/projection/ReactionCount.java
src/main/java/com/attica/athens/domain/chat/dto/request/SendReactionRequest.java
src/main/java/com/attica/athens/domain/chat/dto/response/SendReactionResponse.java
src/main/java/com/attica/athens/domain/chat/exception/NotFoundChatException.java
src/main/java/com/attica/athens/domain/chat/exception/WriterReactionException.java
src/main/java/com/attica/athens/global/handler/WebSocketExceptionHandler.java
src/test/java/com/attica/athens/domain/chat/ChatWebSocketApiIntegrationTest.java
src/test/resources/sql/send-valid-reaction.sql

resolved: #163
- 채팅 반응하기 기능 구현
- 채팅 반응을 저장하는 테이블 설계
- 채팅 반응하기 기능 구현(웹소켓)
- 테스트 작성
- 기능이 올바르게 구현되었는지 확인 부탁드립니다!
리뷰 감사합니다~
<br>
---

채팅 반응하기 기능 구현

---

src/main/java/com/attica/athens/domain/agora/dao/AgoraThumbnailRepository.java
src/main/java/com/attica/athens/domain/agora/domain/AgoraThumbnail.java

- 이미지 저장 도메인 추가
- s3 버킷 생성
- 이후 pr에서 도메인 필드 변경이 있습니다.
<br>
---

thumbnail 도메인 추가

---

src/main/java/com/attica/athens/domain/chat/api/ChatAuthController.java

[#]refactor: 비속어 api get을 post로 변경

---

build.gradle
deploy-prod.sh
src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
src/main/java/com/attica/athens/domain/agora/application/S3ThumbnailService.java
src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
src/main/java/com/attica/athens/domain/agora/dao/AgoraThumbnailRepository.java
src/main/java/com/attica/athens/domain/agora/domain/Agora.java
src/main/java/com/attica/athens/domain/agora/domain/AgoraThumbnail.java
src/main/java/com/attica/athens/domain/agora/dto/SimpleAgoraResult.java
src/main/java/com/attica/athens/domain/agora/dto/SimpleClosedAgoraVoteResult.java
src/main/java/com/attica/athens/global/config/S3Config.java
src/main/resources/application-prod.yml
src/test/java/com/attica/athens/domain/agora/AgoraAuthApiIntegrationTest.java
src/test/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImplTest.java

- 아고라 생성 시 프로필 이미지 업데이트 기능 추가
- 프로밀 이미지 수정 API 추가 (oauth 개발 진행 후 수정)
<br>
---

아고라 생성 API 리팩토링 및 프로필 이미지 수정 API 추가

---

src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java

[배포이슈] 조회 쿼리 이미지 url 필드 추가

---

src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java

- 소켓 메타데이터 응답 오지 않는 부분 수정
- 토픽 구독 시 응답 메시지 전송하는 것으로 수정
<br>
---

소켓 메타데이터 응답 수정

---

docker-compose.blue.yml
docker-compose.green.yml
docker-compose.yml
src/main/resources/application-prod.yml

- redis 환경 변수 설정
- redis를 포함한 배포 스크립트 수정
<br>
---

chore: redis 환경 변수 설정 및 배포 스크립트 수정

---

docker-compose.blue.yml
docker-compose.green.yml
docker-compose.yml

- 브리지 네트워크 사용하여 컨테이너 연결시켜 통신한다.
<br>
---

chore: 배포 스크립트 수정

---

deploy-prod.sh
docker-compose.blue.yml
docker-compose.green.yml
docker-compose.yml

- deploy-prod.sh에 네트워크 생성 로직을 추가
- docker-compose의 blue,green yml에 redis 추가

chore: 배포스크립트 수정

---

docker-compose.yml

- blue, green이 돌아가며 배포될 것이므로 backend(기존) 서비스는 8080 포트 매핑 코드를 제거한다.
<br>
---

chore: 스크립트 수정

---

deploy-prod.sh

chore: 스크립트에 로그 추가

---

deploy-prod.sh
docker-compose.blue.yml
docker-compose.green.yml
docker-compose.yml

- 배포 스크립트 주석 추가
- 컨테이너 중복 생성 문제 해결
<br>
---

fix: 컨테이너 중복 생성 문제 해결

---

deploy-prod.sh

- 새로 컨테이너를 올리기 전에 기존 컨테이너와 중복되지 않게 내리도록 수정
<br>
---

chore: 기존 컨테이너 내리도록 수정

---

deploy-prod.sh

- 새로 배포할때 redis 컨테이너도 함께 내리기
- 볼륨으로 데이터를 저장해놓기 때문에 데이터는 보존된다.
<br>
---

chore: redis 컨테이너도 함께 내리기

---

.github/workflows/backend-cd.yaml
deploy-prod.sh

- `배포 스크립트 수정` : 새로운 컨테이너를 성공적으로 띄운 후 기존 컨테이너를 종료하도록 수정한다. (무중단 배포)
- `github action CD 워크플로우 수정` : github action의 cd 워크플로우에서 배포 스크립트(deploy-prod.sh)가 자동으로 실행되도록 수정한다.
<br>
---

chore: 배포 스크립트 수정 (무중단 배포)

---

deploy-prod.sh

- 배포 스크립트 수정 : 컨테이너 종료시 이전 버전 컨테이너만 종료되도록 수정

fix: 이전 버전 컨테이너만 종료되도록 수정

---

deploy-prod.sh

- stop, rm이 아닌 down을 이용하여 컨테이너 환경을 함께 정리한다
<br>
---

fix: 도커 명령어 수정

---

deploy-prod.sh

- 네트워크 분리 후 컨테이너 제거하기
<br>
---

fix: 컨테이너 제거되지 않는 문제 해결

---

deploy-prod.sh
src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
src/main/java/com/attica/athens/domain/agora/dto/response/AgoraParticipateResponse.java
src/main/java/com/attica/athens/domain/agora/dto/response/UpdateThumbnailResponse.java
src/main/java/com/attica/athens/domain/agora/exception/ImageUpdateAccessDeniedException.java

- 아고라 수정 시 응답 필드에 이미지 path 추가
- 아고라 입장 시 생성한 사용자인지 나타내는 응답 필드 추가
<br>
---

클라이언트 요구사항 반영

---

deploy-prod.sh
src/main/java/com/attica/athens/domain/chat/application/ChatCommandService.java
src/main/java/com/attica/athens/domain/member/api/MemberOpenController.java
src/main/java/com/attica/athens/global/auth/jwt/JwtUtils.java
src/test/java/com/attica/athens/domain/chat/ChatWebSocketApiIntegrationTest.java

- 발견한 에러에 따른 문제 해결
- 캐스팅 에러 해결
- 관찰자도 리액션 보내도록 수정
- oauth 로그인 응답 형식 camel case로 변경
<br>
---

fix: 에러 해결

---

src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
src/main/java/com/attica/athens/domain/agora/dto/response/AgoraTitleResponse.java
src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
src/main/java/com/attica/athens/global/decorator/HeartBeatManager.java
src/main/java/com/attica/athens/global/handler/HeartBeatHandler.java
src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java

- `AgoraTitleResponse`  응답값 color 추가
<br>
---

[#190]refactor: agoraTitleResponse  응답값 color 추가

---

src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java

- 기존 AGORA_ID_INDEX `2`를 `3`으로 수정 **Parsing 부분에서 오류**가 존재했다.
<br>
---

WebSocketEventHandler 상수 수정

---

src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
src/main/java/com/attica/athens/domain/agora/domain/Agora.java
src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
src/main/java/com/attica/athens/domain/agora/vote/domain/KickVote.java
src/main/java/com/attica/athens/domain/agora/vote/dto/KickVoteInfo.java
src/main/java/com/attica/athens/domain/agora/vote/dto/request/KickVoteRequest.java
src/main/java/com/attica/athens/domain/agora/vote/dto/response/KickVoteResult.java
src/main/java/com/attica/athens/domain/agora/vote/dto/response/SendKickResponse.java
src/main/java/com/attica/athens/domain/agora/vote/exception/AlreadyKickVotedException.java
src/main/java/com/attica/athens/domain/agoraMember/dto/response/SendMetaResponse.java
src/main/java/com/attica/athens/domain/chat/domain/ChatType.java
src/test/java/com/attica/athens/domain/vote/AgoraVoteAuthApiIntegrationTest.java
src/test/java/com/attica/athens/domain/vote/AgoraVoteWebSocketApiIntegerationTest.java
src/test/java/com/attica/athens/domain/vote/domain/KickVoteTest.java
src/test/resources/sql/get-agora.sql
src/test/resources/sql/get-base-member.sql

- 유저 추방 투표 관련 서비스 로직과 API 추가
- 아고라 입장 검증 관련 리팩토링
- 관련 테스트 작성
- 아고라 참가자 수 제한이 잘못되어 있어서 수정
- 다른 로직에 영향이 없는지
<br>
---

아고라 유저 추방 투표 API 추가

---

src/main/java/com/attica/athens/domain/agora/application/AgoraService.java

아고라 재입장 검증 수정

---

src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java

두번째 입장 시 에러사항이 해당 부분에서 발생한다고 판단함.
Map에 대한 처리가 문제가 있음.

[#190]refactor: sendMetaToActive 코드 수정.

---

src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
src/main/java/com/attica/athens/domain/agoraMember/dao/AgoraMemberRepository.java

findByAgoraIdAndMemberId에서 여러 값을 응답하는 에러 수정

[#190]refactor: agoraMember non unique 응답 수정

---

src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
src/main/java/com/attica/athens/domain/agora/application/TrendService.java
src/main/java/com/attica/athens/domain/agora/dto/response/ClosedAgoraParticipateResponse.java
src/main/java/com/attica/athens/domain/agora/exception/ActiveAgoraException.java
src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
src/main/java/com/attica/athens/domain/agoraMember/application/AgoraMemberService.java
src/main/java/com/attica/athens/domain/member/api/MemberAuthController.java
src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java

1. filter API 오류
2. 채팅방 인원 변동 정상 동작
3. 탈퇴 api memberId 토큰에서 추출
4. 종료된 채팅방 토큰 없이 입장
<br>
---

[#190]refactor: 이슈 해결

---

deploy-prod.sh
src/main/java/com/attica/athens/domain/member/domain/Member.java
src/main/java/com/attica/athens/global/auth/application/AuthService.java
src/main/java/com/attica/athens/global/auth/config/oauth2/handler/OAuth2AuthenticationSuccessHandler.java

- oauth 로그인시 refresh token을 저장하여 access token 재발급시 사용하도록 한다.
---

fix: 토큰 재발급 오류 수정

---

src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java

resolved: #251
- 투표자, 대상 고유 member id 통일
<br>
---

강제퇴장 투표, 대상 고유 id 통일

---

src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
src/main/java/com/attica/athens/domain/agora/vote/dto/response/SendKickResponse.java
src/main/java/com/attica/athens/domain/agoraMember/dao/AgoraMemberRepository.java

- 클라이언트 요구사항 반영한 응답 스펙 변경
- 문제를 어떻게 해결했는지 간략하게 설명해주세요.
- 리뷰 시 어떤 부분에 집중해야 할지 명시해주세요.
<br>
---

추방 투표 websocket 응답 스펙 변경
